# Basic Settings
title: I4 Ministries Theology
description: Inquire, Intercede, Improve, Inspire.

# Author Information
author:
  name: Marcus Mister
  email: mmister411@gmail.com

# Navigation
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"

# Social Media
twitter_username: marcus.t.mister
github_username: mmister411

# Build Settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Theme
theme: jekyll-theme-midnight

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
